### ISSUE TITLE
Cannot read property 'crypto' of undefined

### ISSUE THREAD

**Issue by pratyushj** [defunctzombie/node-uuid#12]
Hi, 
   I am trying to use `uuid` in my front end project using ES6 import 
```
import uuid from 'uuid'
```
and building it with webpack. However, When I am  running it in the browser I get  `Uncaught TypeError: Cannot read property 'crypto' of undefined` . I tried to debug it and found that the browser does not have a `global` variable unlike node environment which is giving the error  here
```
if (global.crypto && crypto.getRandomValues) {
```

Apologies if there is anything wrong done here

**Comment by defunctzombie** [comment]
The packaging tool is expected to provide the `global` var. Might be a setting in webpack.
