### ISSUE TITLE
License update

### ISSUE THREAD

**Issue by oleastre** [defunctzombie/node-uuid#13]
Could you make a release with the updated package.json so that it appears correctly on npmjs.com and the metadata can be used by automated tools like webjars.org ?

Thanks.

**Comment by vvo** [comment]
What are the required updates to be done?

**Comment by oleastre** [comment]
Your package.json has been updated with 0978094ba920f23d0409a3ebd07c3c6b9f636e21 to correctly add the license tag, but has never been released to npmjs; so the released version is not up to date and automated tools do not see the change.
So no source changes are needed, but just a new release to npmjs.

**Comment by vvo** [comment]
ok will do

**Comment by vvo** [comment]
done

**Comment by oleastre** [comment]
It just work, and the webjar got automatically generated. 
Thanks for your support.
