### ISSUE TITLE
Getting the MAC address from a IPv6 scope-local interface

### ISSUE THREAD

**Issue by mhmeadows63** [defunctzombie/node-uuid#14]
I've found a means to obtain the MAC address within NodeJS.

This module below can be used as follows:
```javascript
var options = { node: require('macaddr') };
uuid = require('uuid').v1(options)
```

If there is no IPv6 interface, the module returns `undefined`, allowing `uuid.v1()` to work normally.

On Windows, interface-randomised-identifiers and privacy settings can cause difficulties, but these can be disabled as follows:

> netsh interface ipv6 set global randomizeidentifiers=disable
> netsh interface ipv6 set privacy state=disable

```javascript
// macaddr.js

module.exports = macaddr(require('os').networkInterfaces());

function macaddr(nics) {
    var nic, index, addr, retn;
    for (nic in nics) { // try to obtain the MAC address from the IPv6 scope-local address
        for (index in nics[nic]) {
            addr = nics[nic][index];
            if (!addr.internal) {
                if (addr.address.indexOf('fe80::') === 0) { // found scope-local
                    retn = retn || addr.address.slice(6).split(/:/).map(function (v, i, a) {
                        return parseInt(v, 16);
                    });
                }
            }
        }
    }
    if (!retn) return;
    
    // eliminate FFFE from xxxx:xxFF:FExx:xxxx and invert bit#41
    retn[5] = retn[3] & 0xff;
    retn[4] = retn[3] >> 8;
    retn[3] = retn[2] & 0xff;
    retn[2] = retn[1] >> 8;
    retn[1] = retn[0] & 0xff;
    retn[0] = retn[0] >> 8 ^ 2;
    return retn;
}
```

**Comment by defunctzombie** [comment]
What is the issue here?

**Comment by mhmeadows63** [comment]
At the time I was unaware that later versions of node delivered mac addresses in the process.networkInterfaces result set. My code originated in the v0.10.x era and I thought to share it before realising that it is no longer necessary.
