### ISSUE TITLE
Support IE11's msCrypto

### ISSUE THREAD

**Issue by bishtawi** [defunctzombie/node-uuid#16]
IE11's crypto object is called `msCrypto` instead of the standard `crypto` name. Need to use that object if it exists.

Source: [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto) and [here](http://caniuse.com/#feat=getrandomvalues)

**Comment by jonhester** [comment]
I only have a Mac and Linux machines handy, but I don't think that is right.

https://msdn.microsoft.com/en-us/library/dn302324(v=vs.85).aspx

**Comment by jonhester** [comment]
Okay, scratch my last comment. I just tested using remote.ie and there is no `crypto`. IE11 does indeed need msCrypto. Why on earth does that msdn page show and IE11 example that doesn't work on IE11 I do not know.
