### ISSUE TITLE
Check if id is a valid uuid?

### ISSUE THREAD

**Issue by axelson** [defunctzombie/node-uuid#19]
Is it possible to use this library to check if a given id is a valid uuid? Or do I need to fall back to regular expressions?

**Comment by defunctzombie** [comment]
Not currently possible via the library. We have considered adding such functionality via regex tho. If you make a PR we can review it.

**Comment by JanKoppe** [comment]
I've provided a simple check function using a regular expression in #21 . This only works for strings right now, let me know if a version that can handle buffers is also needed.

**Comment by axelson** [comment]
Great! That's exactly what I wanted. I don't personally have a need for checking on buffers and I would think it would be less common for this use case.

**Comment by defunctzombie** [comment]
project has moved here and is being consolidated with node-uuid module https://github.com/kelektiv/node-uuid
