### ISSUE TITLE
benchmark.js is not adjusted to not use bufferClass

### ISSUE THREAD

**Issue by tapec** [defunctzombie/node-uuid#8]
Multiple times: TypeError: nodeuuid.BufferClass is not a function

**Comment by defunctzombie** [comment]
A bit more info maybe?

**Comment by tapec** [comment]
~ $ mkdir testcase
~ $ cd testcase
~/testcase $ npm install uuid
/home/foo/testcase
└── uuid@2.0.1 

npm WARN ENOENT ENOENT: no such file or directory, open '/home/foo/testcase/package.json'
npm WARN EPACKAGEJSON testcase No description
npm WARN EPACKAGEJSON testcase No repository field.
npm WARN EPACKAGEJSON testcase No README data
npm WARN EPACKAGEJSON testcase No license field.
~/testcase $ cd node_modules/uuid/benchmark/
~/testcase/node_modules/uuid/benchmark $ npm install
benchmark-uuid@ /home/foo/testcase/node_modules/uuid/benchmark
├── uuid@1.4.1 
└── uuid-js@0.7.4 

~/testcase/node_modules/uuid/benchmark $ node benchmark.js
# v4
nodeuuid.v4() - using node.js crypto RNG: 150966 uuids/second
nodeuuid.v4() - using Math.random() RNG: 144175 uuids/second
nodeuuid.v4('binary'): 180440 uuids/second
/home/foo/testcase/node_modules/uuid/benchmark/benchmark.js:40
  var buffer = new nodeuuid.BufferClass(16);
               ^

TypeError: nodeuuid.BufferClass is not a function
    at Object.<anonymous> (/home/foo/testcase/node_modules/uuid/benchmark/benchmark.js:40:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

**Comment by defunctzombie** [comment]
Haven't touched or bothered with the benchmark file in a long time. Would welcome a PR for fixes if you so feel inclined!
